pipeline:
  name: cd_ruchira
  identifier: cd_ruchira
  projectIdentifier: Lab_Ruchira
  orgIdentifier: training_13thNov
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        description: This is test and we love it
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Ruchira_Lab_Service
          environment:
            environmentRef: org.dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
